services:
    mcz-in-db:
        image: postgres:17
        container_name: mcz-in-db
        hostname: mcz-in-dbb
        ports:
        - "5432:5432"
        volumes:
        - postgres_data:/var/lib/postgresql/data
        networks:
            - mcz-in
        env_file: .env
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 3s
            retries: 5

volumes:
  postgres_data:

networks:
  mcz-in:
    driver: bridge
